#!/usr/bin/env bash
#
# kctl
#   kubectl wrapper, mainly to add namespace arguments according to $KUBENS
#
# scott@smemsh.net
# https://github.com/smemsh/utiladm/
# https://spdx.org/licenses/GPL-2.0
#

kctl ()
{
	local i cmdword nextword nextidx kubectl skipns nsarg nsoff
	local -a cmd

	# stash the -n if user requested, but must come before command word
	for ((i = 1; i <= $#; i++))
	do
		if [[ "${!i:0:1}" == '-' ]]
		then
			if [[ "${!i}" == -n ]]
			then
				nsoff=$i
				let i++
				nsarg="${!i}"
			fi
			continue
		else
			break
		fi
	done

	nextidx=$((i+1))
	cmdword="${!i}"
	nextword="${!nextidx}"
	cmd=("${@:1:i}")

	# if the user asked for -n namespace on cli directly, we kept it, now
	# remove it from the cli args because we will add our own -n
	#
	((nsoff)) && unset "cmd[$((nsoff - 1))]" "cmd[$nsoff]"

	if ((i < $#))
	then case $cmdword in

	(logs)
	cmd+=(-n ${KUBENS:-default})
	;;&

	(delete)
	[[ "$nextword" == nodes ]] && skipns=1
	;&

	(get|describe|events|wait|label|annotate)
	[[ $nsarg ]] && KUBENS=$nsarg
	if [[ $KUBENS == all ]]
	then ((skipns)) || cmd+=(-A)
	else ((skipns)) || cmd+=(-n ${KUBENS:-default})
	fi
	;&

	(*)
	cmd+=("${@:i+1}")
	;;

	esac; fi

	# wrap with kubecolor if present, but not for completions.  not
	# clear why we can't, because if we don't use this script, but
	# merely alias kubectl=kubecolor, then completions work fine.
	# tried to debug this issue, but ran out of time.  TODO
	#
	kubectl=kubectl
	if [[ "$cmdword" != __complete ]]
	then [[ $(type -P kubecolor) ]] && kubectl=kubecolor; fi

	$kubectl "${cmd[@]}"
}

# this will be rarely used, for remaking the 'case' clause in kctl()
knscmds ()
{
	for cmd in $(
	kubectl --help \
	| grep -E ^$'\x20+[a-z]' \
	| field 1 \
	| grep -v kubectl
	)
	do kubectl $cmd --help \
	| grep -q -- --all-namespaces \
	&& echo $cmd
	done
}

main ()
{
	if [[ $(declare -F $invname) ]]
	then $invname "$@"
	else bomb "unimplemented command '$invname'"; fi
}

invname=${0##*/} # 0.9.0
invdir=${0%/*}
main "$@"
