#!/usr/bin/env bash
#
# Builds static Python + OpenSSL
# for major.minor versions: 3.12 + 3.0
#
# scott@smemsh.net
# https://github.com/smemsh/utiladm/
# https://spdx.org/licenses/GPL-2.0
#

set -e
set -o pipefail

[[ ${PWD##*/} == cpython ]]

ssldirbase=/opt/openssl
relocroot=/tmp/relocate
pkgdepot=~/tarbin

logtime=`date +%Y%m%d%H%M%S`
ncpus=`nproc`
arch=`arch`

pyver=$(git describe --tags | awk -F ^v '{print $2}')
sslver=$(ls -1d $ssldirbase* | sort -rV | head -1 | awk -F - '{print $2}')

sslinc=(-I/opt/openssl-$sslver/include/openssl -L/opt/openssl-$sslver/lib64)
sslrule=(_ssl{,.c} ${sslinc[@]} -l:lib{ssl,crypto,z}.a)
hashlibrule=(_hashlib _hashopenssl.c ${sslinc[@]} -l:libcrypto.a)
sqlite3rule=(_sqlite3 $(cd Modules; echo _sqlite/*.c) -l:libsqlite3.a)

buildwatch ()
{
	pv -bntl 2>&1 >|${1:?}-$logtime.log | while read secs lines
	do printf "%s\t\t\r" "$1: ${lines} lines in ${secs%.*}s"
	done; echo
}

configure ()
{
	envstatic=(
	LDFLAGS="'-static -static-libgcc'"
	CFLAGS=-fPIC
	LDSHARED=gcc
	LINKFORSHARED=
	)

	confstatic=(
	--prefix=/opt/python-$pyver
	--enable-optimizations
	--disable-ipv6
	--with-openssl=/opt/openssl-$sslver
	--with-ensurepip=install
	--disable-shared
	--disable-test-modules
	--with-static-libpython
	#--disable-test-modules
	)

	eval "${envstatic[@]}" ./configure "${confstatic[@]}" \
	|& buildwatch configure

	cp config.log config-$logtime.log
}

setup ()
{
	declare -a staticrules=(
	-e '0,/^\*shared\*$/s,shared,static,'
	-e '/^nis\>/d'
	-e '/^_uuid\>/s,(-luuid),-I/usr/include/uuid \1,'
	-e '/^readline\>/s,termcap,tinfo,'
	-e "s,^_ssl\\>.*,${sslrule[*]},"
	-e "s,^_hashlib\\>.*,${hashlibrule[*]},"
	-e '/^_hashlib/a\' -e "${sqlite3rule[*]}"
	-e '/^_tkinter\>/d'
	-e '/^_curses\>/s,(-lncurses).*-ltermcap,\1w -ltinfo,'
	-e '/^_curses_panel\>/s,(-lpanel),\1w,'
	-e '/^_curses_panel\>/s,(-lncurses),\1w -ltinfo,'
	-e '/^\*shared\*$/d'
	-e '/^_test/d'
	-e '/^\*disabled\*$/a\' -e 'nis\n_tkinter\nspwd'
	#-e "s,^(_testcapi\\>.*),\\1 $(echo _testcapi/*.c),"
	#-e '/^_testsinglephase\>/a\'
	#-e '_testclinic _testclinic.c'
	)

	cd Modules
	sed -n -r 's/^#([a-z_\*].*)$/\1/p' Setup >| Setup.local
	sed -i -r "${staticrules[@]}" Setup.local
	cd ..
}

build ()
{
	make -j$ncpus \
	|& buildwatch build
}

package ()
{
	test -e $relocroot && false

	make DESTDIR=$relocroot install \
	|& buildwatch install

	tar \
	-C $relocroot \
	-cvaf $pkgdepot/python-${pyver}_static_${arch}_opt.tar.zst \
	--owner=0 --group=0 \
	opt \
	|& buildwatch package
}

main ()
{
	echo "building static python: $pyver, openssl: $sslver, cores: $ncpus"

	printf cleanup...
	make distclean &>/dev/null
	rm -rf $relocroot
	echo done

	configure
	setup
	build
	package

	echo "build completed in ${SECONDS}s"
}

main "$@"
